name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  flutter_map: ^5.0.0
  http: ^1.2.2
  provider: ^6.1.2
  signature: ^5.0.0
  shared_preferences: ^2.0.15
  connectivity_plus: ^5.0.1 # Asegúrate de usar la última versión estable
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
